/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rpg;

/**
 *
 * @author GABRIELGARCEZDEOLIVE
 */
public class SheetForm extends javax.swing.JFrame {

    /**
     * Creates new form SheetForm
     */
    public SheetForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        nameField = new javax.swing.JTextField();
        heightField = new javax.swing.JTextField();
        weightField = new javax.swing.JTextField();
        ageField = new javax.swing.JTextField();
        abilityLabel = new javax.swing.JLabel();
        ability1 = new javax.swing.JCheckBox();
        ability2 = new javax.swing.JCheckBox();
        ability3 = new javax.swing.JCheckBox();
        ability4 = new javax.swing.JCheckBox();
        ability5 = new javax.swing.JCheckBox();
        ability6 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        btnElf = new javax.swing.JRadioButton();
        btnDwarf = new javax.swing.JRadioButton();
        btnDragonborn = new javax.swing.JRadioButton();
        btnOrc = new javax.swing.JRadioButton();
        btnHuman = new javax.swing.JRadioButton();
        btnVampire = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        classBox = new javax.swing.JComboBox<>();
        btnMinotaur = new javax.swing.JRadioButton();
        btnWarewolf = new javax.swing.JRadioButton();
        btnCreate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameField.setText("Name:");

        heightField.setText("Height:");

        weightField.setText("Weight:");

        ageField.setText("Age:");

        abilityLabel.setText("Abilities:");

        ability1.setText("Ability");
        ability1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ability1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ability1ActionPerformed(evt);
            }
        });

        ability2.setText("Ability");
        ability2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        ability3.setText("Ability");
        ability3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ability3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ability3ActionPerformed(evt);
            }
        });

        ability4.setText("Ability");
        ability4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        ability5.setText("Ability");
        ability5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ability5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ability5ActionPerformed(evt);
            }
        });

        ability6.setText("Ability");
        ability6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ability6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ability6ActionPerformed(evt);
            }
        });

        jLabel2.setText("Race:");

        buttonGroup1.add(btnElf);
        btnElf.setText("Elf");
        btnElf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElfActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnDwarf);
        btnDwarf.setText("Dwarf");
        btnDwarf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDwarfActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnDragonborn);
        btnDragonborn.setText("Dragonborn");
        btnDragonborn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDragonbornActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnOrc);
        btnOrc.setText("Orc");

        buttonGroup1.add(btnHuman);
        btnHuman.setText("Human");

        buttonGroup1.add(btnVampire);
        btnVampire.setText("Vampire");

        jLabel3.setText("Class:");

        classBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mage", "Ranger", "Babáro", "Cleric", "Druid", "Paladin", "Necromancer" }));
        classBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classBoxActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnMinotaur);
        btnMinotaur.setText("Minotaur");
        btnMinotaur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinotaurActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnWarewolf);
        btnWarewolf.setText("Werewolf");

        btnCreate.setText("Create Character");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ageField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(heightField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(weightField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(classBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(abilityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ability3, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(ability1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ability2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ability4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ability5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ability6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnElf, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHuman, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDwarf, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOrc, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDragonborn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVampire, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnMinotaur, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnWarewolf, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCreate)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnElf)
                            .addComponent(btnHuman))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDwarf)
                            .addComponent(btnOrc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDragonborn)
                            .addComponent(btnVampire))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMinotaur)
                            .addComponent(btnWarewolf)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(heightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(weightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(classBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(abilityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ability1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ability4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ability2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ability5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ability3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ability6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(btnCreate)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ability3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ability3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ability3ActionPerformed

    private void ability6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ability6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ability6ActionPerformed

    private void ability5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ability5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ability5ActionPerformed

    private void ability1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ability1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ability1ActionPerformed

    private void btnDragonbornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDragonbornActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDragonbornActionPerformed

    private void btnElfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnElfActionPerformed

    private void btnDwarfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDwarfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDwarfActionPerformed

    private void btnMinotaurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinotaurActionPerformed

    }//GEN-LAST:event_btnMinotaurActionPerformed

    private void classBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classBoxActionPerformed
        String rpgClass = (String) classBox.getSelectedItem();
        String teste = ability1.getText();
        
        System.out.println(teste);
                
        System.out.println(buttonGroup1.getSelection());
        
        switch(rpgClass){
            case "Mage":
                ability1.setText("Magic Hand");
                ability2.setText("Fly");
                ability3.setText("Magic Missiles");
                ability4.setText("Fire Ball");
                ability5.setText("Magic Bullet: Brutal");
                ability6.setText("Magic Bullet: Fused Shot");
                break;
            case "Ranger":
                ability1.setText("Magic Bullet: Precise");
                ability2.setText("Teleport");
                ability3.setText("Rage");
                ability4.setText("Long Range Magic");
                ability5.setText("Magic Missile V2");
                ability6.setText("Mark");                
                break;
            case "Babáro":
                ability1.setText("Rage");
                ability2.setText("Second Wind");
                ability3.setText("Action Surge");
                ability4.setText("Teleport");
                ability5.setText("Way of The Bear");
                ability6.setText("Magic Shield");                
                break;
            case "Cleric":
                ability1.setText("Cure");
                ability2.setText("Cure Wand");
                ability3.setText("Healing World");
                ability4.setText("Divine Smite");
                ability5.setText("Blessed Weapon");
                ability6.setText("Rage");                
                break;
            case "Paladin":
                ability1.setText("Smite");
                ability2.setText("The Diviniest of Smites");
                ability3.setText("Fire Ball");
                ability4.setText("Wish a God / Wish a Devil");
                ability5.setText("Pray");
                ability6.setText("Holy Fire Ball");                
                break;
            case "Necromancer":
                ability1.setText("Revivify");
                ability2.setText("Destroy Undead");
                ability3.setText("Cure Wounds");
                ability4.setText("Healing World");
                ability5.setText("Light of Clerics");
                ability6.setText("Bless");                
                break;
            case "Druid":
                ability1.setText("Break Element");
                ability2.setText("Fire Ball");
                ability3.setText("Rise Infernal");
                ability4.setText("Rage");
                ability5.setText("Revivify");
                ability6.setText("Oath Breaker");                
                break;
            default:
                break;
        }
    }//GEN-LAST:event_classBoxActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        String name = nameField.getText();
        String age = ageField.getText();
        String weight = weightField.getText();
        String height = heightField.getText();
        String rpgClass = (String) classBox.getSelectedItem();
        String abilities = "";
        String race = "";
        
                
        if(ability1.isSelected()){
            abilities+=ability1.getText()+" | ";
        }
        if(ability2.isSelected()){
            abilities+=ability2.getText()+" | ";
        }        
        if(ability3.isSelected()){
            abilities+=ability3.getText()+" | ";
        }
        if(ability4.isSelected()){
            abilities+=ability4.getText()+" | ";
        }
        if(ability5.isSelected()){
            abilities+=ability5.getText()+" | ";
        }
        if(ability6.isSelected()){
            abilities+=ability6.getText()+" | ";
        } 

        
    }//GEN-LAST:event_btnCreateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SheetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SheetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SheetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SheetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SheetForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ability1;
    private javax.swing.JCheckBox ability2;
    private javax.swing.JCheckBox ability3;
    private javax.swing.JCheckBox ability4;
    private javax.swing.JCheckBox ability5;
    private javax.swing.JCheckBox ability6;
    private javax.swing.JLabel abilityLabel;
    private javax.swing.JTextField ageField;
    private javax.swing.JButton btnCreate;
    private javax.swing.JRadioButton btnDragonborn;
    private javax.swing.JRadioButton btnDwarf;
    private javax.swing.JRadioButton btnElf;
    private javax.swing.JRadioButton btnHuman;
    private javax.swing.JRadioButton btnMinotaur;
    private javax.swing.JRadioButton btnOrc;
    private javax.swing.JRadioButton btnVampire;
    private javax.swing.JRadioButton btnWarewolf;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> classBox;
    private javax.swing.JTextField heightField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField weightField;
    // End of variables declaration//GEN-END:variables
}
