/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package harrypotterjtable;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GABRIELGARCEZDEOLIVE
 */
public class School extends javax.swing.JFrame {

    private DefaultTableModel newStudentTable, TableSlyt, TableGrif, TableRaven, TableHuffle;
    DefaultTableModel[] tablesModel;
    JTable[] tables;
    int grifStudents;
    int slytStudents;
    int huffleStudents;
    int ravenStudents;

    /**
     * Creates new form Escola
     */
    public School(Student[] students) {
        initComponents();
        newStudentTable = new DefaultTableModel();
        TableSlyt = new DefaultTableModel();
        TableGrif = new DefaultTableModel();
        TableRaven = new DefaultTableModel();
        TableHuffle = new DefaultTableModel();
                
        tableNewStudents.setModel(newStudentTable);
        tableSlyt.setModel(TableSlyt);
        tableGrif.setModel(TableGrif);
        tableRaven.setModel(TableRaven);
        tableHuffle.setModel(TableHuffle);
        
        
        
        this.tables = new JTable[]{tableSlyt, tableGrif, tableRaven, tableHuffle};
        
        this.tablesModel = new DefaultTableModel[]{TableSlyt, TableGrif, TableRaven, TableHuffle, newStudentTable};
        
        for(DefaultTableModel table: tablesModel){
        table.addColumn("Name");
        table.addColumn("Personality");        
        }
        
        for(Student student : students){
            
            newStudentTable.addRow(new Object[]{student.getName(), student.getPersonality()});
        }
        
    }
    
    public void VerifyStudents(){
        grifStudents = TableGrif.getRowCount();
        slytStudents = TableSlyt.getRowCount();
        huffleStudents = TableHuffle.getRowCount();
        ravenStudents = TableRaven.getRowCount();
        
        labelGrif.setText("Gryffindor: "+grifStudents+" Students");
        labelSlyt.setText("Slytherin: "+slytStudents+" Students");
        labelRaven.setText("Ravenclaw: "+ravenStudents+" Students");
        labelHuffle.setText("Hufflepuff: "+huffleStudents+" Students");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableNewStudents = new javax.swing.JTable();
        btnSelector = new javax.swing.JButton();
        btnExpulse = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableGrif = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableSlyt = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        tableRaven = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        tableHuffle = new javax.swing.JTable();
        labelRaven = new javax.swing.JLabel();
        labelHuffle = new javax.swing.JLabel();
        labelGrif = new javax.swing.JLabel();
        labelSlyt = new javax.swing.JLabel();
        labelStudents = new javax.swing.JLabel();

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Personality"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        tableNewStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Personality"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableNewStudents);

        btnSelector.setText("Selector Hat");
        btnSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectorActionPerformed(evt);
            }
        });

        btnExpulse.setText("Expulse");
        btnExpulse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpulseActionPerformed(evt);
            }
        });

        tableGrif.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Personality"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tableGrif);

        tableSlyt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Personality"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tableSlyt);

        tableRaven.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Personality"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tableRaven);

        tableHuffle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Personality"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane8.setViewportView(tableHuffle);

        labelRaven.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRaven.setText("Ravenclaw:");

        labelHuffle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHuffle.setText("Hufflepuff:");

        labelGrif.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGrif.setText("Griffyndor:");

        labelSlyt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSlyt.setText("Slytherin:");

        labelStudents.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelStudents.setText("New Students");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelRaven, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelHuffle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelGrif, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnSelector, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelSlyt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExpulse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(labelStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExpulse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSlyt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelGrif, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRaven, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHuffle, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectorActionPerformed
        int line = tableNewStudents.getSelectedRow();
        String choosenPersonality = tableNewStudents.getValueAt(line, 1).toString();
        String choosenName = tableNewStudents.getValueAt(line, 0).toString();
        System.out.println(choosenPersonality);
        
        switch(choosenPersonality){
            case "Leal":
                TableHuffle.addRow(new Object[]{choosenName, choosenPersonality});
                break;
            case "Ousado":
                TableGrif.addRow(new Object[]{choosenName, choosenPersonality});
                break;
            case "Astuto":
                TableSlyt.addRow(new Object[]{choosenName, choosenPersonality});
                break;
            case "Inteligente":
                TableRaven.addRow(new Object[]{choosenName, choosenPersonality});
                break; 
            case "Astuta":
                TableSlyt.addRow(new Object[]{choosenName, choosenPersonality});
                break;
            case "Ousada":
                TableGrif.addRow(new Object[]{choosenName, choosenPersonality});
                break;

        }
        newStudentTable.removeRow(line);
        VerifyStudents();
    }//GEN-LAST:event_btnSelectorActionPerformed

    private void btnExpulseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpulseActionPerformed
        
        if (tableSlyt.getSelectedRow() != -1){
            TableSlyt.removeRow(tableSlyt.getSelectedRow());
        } else if (tableGrif.getSelectedRow() != -1){
            TableGrif.removeRow(tableGrif.getSelectedRow());
        } else if (tableRaven.getSelectedRow() != -1){
            TableRaven.removeRow(tableRaven.getSelectedRow());
        } else if(tableHuffle.getSelectedRow() != -1){
            TableHuffle.removeRow(tableHuffle.getSelectedRow());
        } else {
            System.out.println("Deu ruim"); 
        }
        
        VerifyStudents();
    }//GEN-LAST:event_btnExpulseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(School.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(School.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(School.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(School.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new School().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExpulse;
    private javax.swing.JButton btnSelector;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTable4;
    private javax.swing.JLabel labelGrif;
    private javax.swing.JLabel labelHuffle;
    private javax.swing.JLabel labelRaven;
    private javax.swing.JLabel labelSlyt;
    private javax.swing.JLabel labelStudents;
    private javax.swing.JTable tableGrif;
    private javax.swing.JTable tableHuffle;
    private javax.swing.JTable tableNewStudents;
    private javax.swing.JTable tableRaven;
    private javax.swing.JTable tableSlyt;
    // End of variables declaration//GEN-END:variables
}
